# Generated by Django 4.2.7 on 2023-12-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('text2', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('text3', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('like', models.BooleanField(default=False)),
                ('data', models.CharField(max_length=10)),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.category')),
            ],
        ),
    ]
